
title: Your awesome title
author: GitHub User
email: mpicanco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Marco Picanco github website python data analisys openfoam.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mpicanco # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
